// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const SecretFilesSchema = z.object({
  id: z.string().uuid(),
  envId: z.string().uuid(),
  secretPath: z.string(),
  name: z.string(),
  localPath: z.string().nullable().optional(),
  description: z.string().nullable().optional(),
  sha256: z.string(),
  sizeBytes: z.number(),
  encryptedContent: z.unknown(),
  version: z.number().default(1).nullable().optional(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TSecretFiles = z.infer<typeof SecretFilesSchema>;
export type TSecretFilesInsert = Omit<z.input<typeof SecretFilesSchema>, TImmutableDBKeys>;
export type TSecretFilesUpdate = Partial<Omit<z.input<typeof SecretFilesSchema>, TImmutableDBKeys>>;
